# docker-compose.yml
services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --watch --force_polling --incremental --host 0.0.0.0 --port 4001
    ports:
      - "4001:4001"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development