# .github/workflows/production.yml
name: Deploy Production

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Jekyll site
        run: |
          docker run --rm \
            --volume="${GITHUB_WORKSPACE}:/srv/jekyll" \
            --env JEKYLL_ENV=production \
            --env JEKYLL_UID="$(id -u)" \
            --env JEKYLL_GID="$(id -g)" \
            jekyll/builder:4 \
            jekyll build

      - name: Deploy Production
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: gh-pages
          umbrella-dir: lgi
          comment: false
          keep-files: true